name: Build and Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: List available Python versions
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          python -c "import sys; print(sys.version)"

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0  # Use an appropriate Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --deploy --ignore-pipfile
      
      - name: Test with pytest
        run: |
          pipenv run pytest

